import unittest
from unittest.mock import patch

import main


SAMPLE_DATA = {
    "url": "https://www.instagram.com/p/ABC123/",
    "owner": {"username": "tester"},
    "post_type": "carousel",
    "date": "2026-03-01T00:00:00",
    "date_local": None,
    "likes": 1,
    "comments_count": 2,
    "media_count": 1,
    "caption": "",
    "accessibility_caption": "Autogenerated summary",
    "hashtags": [],
    "mentions": [],
    "media": [{"index": 1, "type": "image"}],
    "slides": [],
    "ocr_text": [],
}


class MainTests(unittest.TestCase):
    @patch.object(main.console, "print")
    def test_display_results_hides_accessibility_caption_by_default(self, mock_print) -> None:
        main.display_results(SAMPLE_DATA)

        printed_titles = [
            call.args[0].title
            for call in mock_print.call_args_list
            if call.args and hasattr(call.args[0], "title")
        ]
        self.assertNotIn("Accessibility Caption", printed_titles)

    @patch.object(main.console, "print")
    def test_display_results_shows_accessibility_caption_when_enabled(self, mock_print) -> None:
        main.display_results(SAMPLE_DATA, show_accessibility=True)

        printed_titles = [
            call.args[0].title
            for call in mock_print.call_args_list
            if call.args and hasattr(call.args[0], "title")
        ]
        self.assertIn("Accessibility Caption", printed_titles)


if __name__ == "__main__":
    unittest.main()
