"""Shared constants for the extractor pipeline."""

DEFAULT_OCR_LANG = "eng"
DEFAULT_OCR_PSM = 6
DEFAULT_OCR_MIN_CONFIDENCE = 30.0
DEFAULT_FETCH_ATTEMPTS = 3
DEFAULT_VIDEO_FRAME_INTERVAL_SECONDS = 1.0
SHORT_VIDEO_FRAME_INTERVAL_SECONDS = 0.5
SHORT_VIDEO_DURATION_THRESHOLD_SECONDS = 15.0
SCENE_SIMILARITY_THRESHOLD = 0.9
SCENE_TOKEN_OVERLAP_THRESHOLD = 0.7
MIN_SCENE_CONFIDENCE = 60.0
MIN_SCENE_MEANINGFUL_TOKENS = 4
REQUEST_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/133.0.0.0 Safari/537.36"
    )
}
